version: "3.4"

services:
  nativeTesterService:
    image: native_image
    build:
      context: .
      dockerfile: native.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  jsonTesterService:
    image: json_image
    build:
      context: .
      dockerfile: json.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  xmlTesterService:
    image: xml_image
    build:
      context: .
      dockerfile: xml.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  protoTesterService:
    image: proto_image
    build:
      context: .
      dockerfile: proto.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  avroTesterService:
    image: avro_image
    build:
      context: .
      dockerfile: avro.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  yamlTesterService:
    image: yaml_image
    build:
      context: .
      dockerfile: yaml.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  mpackTesterService:
    image: mpack_image
    build:
      context: .
      dockerfile: mpack.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  proxyService:
    image: proxy_image
    build:
      context: .
      dockerfile: proxy.dockerfile  
    environment:
      NUM_TESTERS: 7
      PROXY_PORT: 2000
      NATIVE_HOST: nativeTesterService
      NATIVE_PORT: 2001
      JSON_HOST: jsonTesterService
      JSON_PORT: 2001
      XML_HOST: xmlTesterService
      XML_PORT: 2001
      PROTO_HOST: protoTesterService
      PROTO_PORT: 2001
      AVRO_HOST: avroTesterService
      AVRO_PORT: 2001
      YAML_HOST: yamlTesterService
      YAML_PORT: 2001
      MPACK_HOST: mpackTesterService
      MPACK_PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001
    ports:
      - 2000:2000/udp
    depends_on:
      - nativeTesterService
      - jsonTesterService
      - xmlTesterService
      - protoTesterService
      - avroTesterService
      - yamlTesterService
      - mpackTesterService