version: "3.4"

services:
  nativeTesterService:
    image: yulikdaniel/nativetest
    build:
      context: .
      dockerfile: native.dockerfile
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  jsonTesterService:
    image: yulikdaniel/jsontest
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  xmlTesterService:
    image: yulikdaniel/xmltest
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  protoTesterService:
    image: yulikdaniel/prototest
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  avroTesterService:
    image: yulikdaniel/avrotest
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  yamlTesterService:
    image: yulikdaniel/yamltest
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  mpackTesterService:
    image: yulikdaniel/mpacktest
    environment:
      PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001

  proxyService:
    image: proxy_image
    build:
      context: .
      dockerfile: proxy.dockerfile  
    environment:
      NUM_TESTERS: 7
      PROXY_PORT: 2000
      NATIVE_HOST: nativeTesterService
      NATIVE_PORT: 2001
      JSON_HOST: jsonTesterService
      JSON_PORT: 2001
      XML_HOST: xmlTesterService
      XML_PORT: 2001
      PROTO_HOST: protoTesterService
      PROTO_PORT: 2001
      AVRO_HOST: avroTesterService
      AVRO_PORT: 2001
      YAML_HOST: yamlTesterService
      YAML_PORT: 2001
      MPACK_HOST: mpackTesterService
      MPACK_PORT: 2001
      MULTICAST_HOST: 224.3.29.71
      MULTICAST_PORT: 2001
    ports:
      - 2000:2000/udp
    depends_on:
      - nativeTesterService
      - jsonTesterService
      - xmlTesterService
      - protoTesterService
      - avroTesterService
      - yamlTesterService
      - mpackTesterService